name = "countdown"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "COUNTDOWNS"
id = "e521e6f0399340bf8f4d59c5724fe4f3"

[[kv_namespaces]]
binding = "LICENSES"
id = "9d1298d06d7540d8a5c6b6c0904e0ff8"
